// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajdtcqwlufbasfgdxrii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqZHRjcXdsdWZiYXNmZ2R4cmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDc4NzksImV4cCI6MjA1ODQ4Mzg3OX0.NVAODQz1qw4oNJl_DSFsAUTgVWGQGlV-iUQ0WxBGN_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);